### PR TITLE
migration: typescript

### PR DESCRIPTION
**Pull request by ghost**
reusing previous draft pr for migration:

1. Refactor code to TS and vitest (using `npx ts-migration-helper prompt`.)
2. Add comments, variable defs and rename variables to make it readable

### CODE REVIEW

**Comment by targos** [comment]
I'm sorry, but the TS migration makes the actual fixes impossible to identify/review 😞

**Comment by ghost** [comment]
> I'm sorry, but the TS migration makes the actual fixes impossible to identify/review disappointed

I see. I'll check how to fix this.

**Comment by targos** [comment]
Can you point me to a part of the diff or relevant commit?

**Comment by ghost** [comment]
> Can you point me to a part of the diff or relevant commit?

I've done it below, just in case that you didnt get notif. I may split this into 3 PRs instead, 

* Readme changes
* fix and tests
* migration to ts

I think the reason for the [missing diffs was this.](https://stackoverflow.com/questions/433111/how-to-make-git-mark-a-deleted-and-a-new-file-as-a-file-move)

Does this strategy sound fine to you @targos ? I'm just trying to avoid mistakes, and don't really know if there is a better way.

**Pull request closed without merging**
